### PR TITLE
Entity Job Translation for mod such as WTHIT, JADE etc

### PR DESCRIPTION
**Pull request by ardissaps**
It translate all villager with vanilla job and some mods job (More Villagers, Charm, Friends & Foe, BYG, Etched)

Btw this is what caused me to be kicked from Discord Server by admin anime girl picture.

### CODE REVIEW

**Comment by ardissaps** [comment]
Before :
unknown

After : 
image

**Comment by CDAGaming** [comment]
Marked as personal fix, while noted, we'll explore in code to see whats actually going wrong, but no guarantees on a fix until at leaat 7.4

**Comment by Luke100000** [comment]
Thanks for your effort, but I can fix it from MCAs side:
WTHIT and co uses the entity type getter, which is overwritten by Villager. We can overwrite it too to use the profession keys of vanilla villagers.

**Comment by Luke100000** [comment]
For whatever reason, WTHIS doesnt show me professions at all so I can't test it, but it should work not. Assuming I didn't made a typo

**Comment by CDAGaming** [comment]
Push the commit, I can probably find a way to test it somehow xD
That or @ardissaps can demo the fix too

**Comment by CDAGaming** [comment]
image
Works as intended, closed as resolved

**Comment by ardissaps** [comment]
> Thanks for your effort, but I can fix it from MCAs side: WTHIT and co uses the entity type getter, which is overwritten by Villager. We can overwrite it too to use the profession keys of vanilla villagers.

No problem, idk how to report this properly so I just pr it while learning. :D 


> Works as intended, closed as resolved

Nice! Thank you very much! :p 

(UTC+7)

**Pull request closed without merging**
