### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by mylittleblover**
This is the Chinese version produced by Lite studio. I hope the author can adopt it.

### CODE REVIEW

**Comment by Luke100000** [comment]
Hi! Just to make sure: do you have the right to publish Lite Studios work? If yes, please upload the file here https://crowdin.com/project/minecraft-comes-alive-2 as we use a third party site to organize translations. (in your case, select Chinese, click the 3 dots on lang.json and click upload translations, pass the zn_cn.json). Thanks!

**Comment by mylittleblover** [comment]
OK,thank you!

**Comment by mylittleblover** [comment]
> Hi! Just to make sure: do you have the right to publish Lite Studios work? If yes, please upload the file herehttps://crowdin.com/project/minecraft-comes-alive-2as we use a third party site to organize translations. (in your case, select Chinese, click the 3 dots on lang.json and click upload translations, pass the zn_cn.json). Thanks!

finish

**Comment by Luke100000** [comment]
Thanks! Received and will be added in the next build!

**Comment by mylittleblover** [comment]
> Thanks! Received and will be added in the next build!

Some of the dialogue texts are still in English and will be revised tomorrow

**Comment by mylittleblover** [comment]
> Thanks! Received and will be added in the next build!

Also, I hope you can mark Lite studio when adding text, which is conducive to our reputation

**Comment by mylittleblover** [comment]
> Thanks! Received and will be added in the next build!

OK,Now texts are all done.

**Comment by Luke100000** [comment]
> > Thanks! Received and will be added in the next build!
> 
> OK,Now texts are all done.

Awesome, thanks a lot!

**Comment by mylittleblover** [comment]
> > > Thanks! Received and will be added in the next build!
> > 
> > 
> > OK,Now texts are all done.
> 
> Awesome, thanks a lot!

Unfortunately, there are still many texts that cannot be translated into Chinese, because these texts do not exist in multilingual folders. Our studio wants to make a fully translated version and publish it to MCBBS. We will indicate the original author. If you are willing to give us the right to publish, we will thank you very much

**Comment by Luke100000** [comment]
> > > > Thanks! Received and will be added in the next build!
> > > 
> > > 
> > > OK,Now texts are all done.
> > 
> > 
> > Awesome, thanks a lot!
> 
> Unfortunately, there are still many texts that cannot be translated into Chinese, because these texts do not exist in multilingual folders. Our studio wants to make a fully translated version and publish it to MCBBS. We will indicate the original author. If you are willing to give us the right to publish, we will thank you very much

The lang files in this repo are up to date, the crowdin translation is close to being up to date. I see that 97% has been translated by various translators.
This project's license allows you to publish it yourself, with the condition of making your work (the translation) open-source (GPL 3.0) too. (e.g. by maintaining a fork of my repo)

This is the used licence: https://github.com/Luke100000/minecraft-comes-alive/blob/1.16_architectury/LICENSE

**Comment by mylittleblover** [comment]
> > > > > 谢谢！收到，并将添加在下一个建设！
> > > > 
> > > > 
> > > > 好了，现在短信都发完了。
> > > 
> > > 
> > > 太棒了，非常感谢！
> > 
> > 
> > 遗憾的是，仍有许多文本无法翻译成中文，因为这些文本不存在于多语言文件夹中。我们的工作室想做一个完整的翻译版本，并发布给MCBBS。我们会注明原作者。如果您愿意给我们出版权，我们将非常感谢
> 
> 这个repo中的lang文件是最新的，crowdin翻译也接近最新。我看到有97％是由不同的译者翻译的。这个项目的许可证允许你自己发布它，条件是让你的作品（翻译）开源（GPL 3.0）。（例如，通过维护我的回购叉）
> 
> 以下是旧牌照：https://github.com/Luke100000/minecraft-comes-alive/blob/1.16_architectury/LICENSE

Thank you very much!

**Comment by mylittleblover** [comment]
> > > > > Thanks! Received and will be added in the next build!
> > > > 
> > > > 
> > > > OK,Now texts are all done.
> > > 
> > > 
> > > Awesome, thanks a lot!
> > 
> > 
> > Unfortunately, there are still many texts that cannot be translated into Chinese, because these texts do not exist in multilingual folders. Our studio wants to make a fully translated version and publish it to MCBBS. We will indicate the original author. If you are willing to give us the right to publish, we will thank you very much
> 
> The lang files in this repo are up to date, the crowdin translation is close to being up to date. I see that 97% has been translated by various translators. This project's license allows you to publish it yourself, with the condition of making your work (the translation) open-source (GPL 3.0) too. (e.g. by maintaining a fork of my repo)
> 
> This is the used licence: https://github.com/Luke100000/minecraft-comes-alive/blob/1.16_architectury/LICENSE

But I have a question,where areblueprint's texts such as"Building Catalog" and villager editor's texts such as "General","Body"?I couldn't find it.

**Comment by Luke100000** [comment]
In the lang file as everything else: https://github.com/Luke100000/minecraft-comes-alive/blob/1.16_architectury/common/src/main/resources/assets/mca/lang/en_us.json
We have 2 more lang files to separate dialogues and books, but the building catalog is in the main lang file.

**Comment by mylittleblover** [comment]
> In the lang file as everything else: https://github.com/Luke100000/minecraft-comes-alive/blob/1.16_architectury/common/src/main/resources/assets/mca/lang/en_us.json We have 2 more lang files to separate dialogues and books, but the building catalog is in the main lang file.

where are they?

**Comment by mylittleblover** [comment]
> In the lang file as everything else: https://github.com/Luke100000/minecraft-comes-alive/blob/1.16_architectury/common/src/main/resources/assets/mca/lang/en_us.json We have 2 more lang files to separate dialogues and books, but the building catalog is in the main lang file.

**Comment by Luke100000** [comment]
Ouf, those are hardcoded strings I forgot about, my bad. They will appear 7.0.7 :)

**Comment by mylittleblover** [comment]
> Ouf, those are hardcoded strings I forgot about, my bad. They will appear 7.0.7 :)

Please hurry up,thank you.

**Comment by mylittleblover** [comment]
> Ouf, those are hardcoded strings I forgot about, my bad. They will appear 7.0.7 :)

7.0.7 texts has been upload on Crowdin

**Comment by mylittleblover** [comment]
> Ouf, those are hardcoded strings I forgot about, my bad. They will appear 7.0.7 :)

And please add mylittleblover,Mastiff and Prophet to the translater.json

**Pull request closed without merging**
