### PR TITLE
Update Civil Registry [edit: Rose gold book] to use gold instead of rose gold

### PR DESCRIPTION
**Pull request by DavidParker682**
Since Rose Gold was removed from survival mode, the book can no longer be crafted.

### CODE REVIEW

**Comment by Luke100000** [comment]
Rose Gold was not removed tho :)
Blend it: https://github.com/Luke100000/minecraft-comes-alive/blob/1.20.1/common/src/main/resources/data/mca/recipes/rose_gold_dust.json
And melt it: https://github.com/Luke100000/minecraft-comes-alive/blob/1.20.1/common/src/main/resources/data/mca/recipes/rose_gold_ingot_smelting.json

**Comment by DavidParker682** [comment]
Ok my bad, I didn't check the code and didn't think to get the dust first. Also a bit odd that I got the book telling me how to make Rose Gold after I had made the first ingot. Maybe make the book craftable using gold and copper.

**Comment by Luke100000** [comment]
Oh yes, that makes sense

**Comment by DavidParker682** [comment]
How does this look now, changed the book recipe to copper and gold ingots.

**Comment by Luke100000** [comment]
Better :) However, gold and copper are from the minecraft namespace, not mca

**Comment by DavidParker682** [comment]
Very sorry, quite new to modding in that I have never done it before, but nice to start small.

**Comment by Luke100000** [comment]
Thank you!

**Pull request merged**
