### PR TITLE
Spanish (Chilean) translation

### PR DESCRIPTION
**Pull request by DracoExE**
Initial files for the es_cl translation (mostly the same as es_es files with some minor modifications)

### CODE REVIEW

**Comment by Luke100000** [comment]
Hi, thanks! How similar are those two languages? Usually, translation happens over https://crowdin.com/project/minecraft-comes-alive-2, importing Chilean with "wrong" translations may cause confusion. Any ideas?

**Comment by DracoExE** [comment]
> 

They're pretty much the same, but we still have some small differences like The Grim Reaper. In Spain is called "La Parca", while here in Chile (and maybe in other latin-american countries) is more commonly known as "La Muerte". In any case, probably any spanish speaker will understand the different variations of spanish regarding the country they're :)

If needed, I can upload the same translations if there're the es_cl files at crowdin in order to avoid overwritting the es_es :)

**Comment by Luke100000** [comment]
Okay. Please decide yourself as you are more familiar with this: should we use Spanish as the base for Chilean or start from scratch (using your adaptions).

**Comment by DracoExE** [comment]
> Okay. Please decide yourself as you are more familiar with this: should we use Spanish as the base for Chilean or start from scratch (using your adaptions).

The best and easiest way is to use Spanish as te base for Chilean, then modify the words and phrases (which is basically what I did with the files of this pull request)

**Comment by Luke100000** [comment]
Alright, thanks! I merged and synced it with Crowdin. From now on please use crowdin for changes or updates because it is not possible to properly sync changes made on the repo directly.

**Pull request merged**
